package mr

const (
	TASK_STATUS_UNSTARTED = 0
	TASK_STATUS_PROCESS   = 1
	TASK_STATUS_FINISHED  = 2
)

const (
	STATUS_MAPPER_NEEDED   = 0
	STATUS_MAPPER_PROCESS  = 1
	STATUS_REDUCER_NEEDED  = 2
	STATUS_REDUCER_PROCESS = 3
	STATUS_FINISHED        = 4
)

const (
	ROLE_QUIT    = 0
	ROLE_MAPPER  = 1
	ROLE_REDUCER = 2
	ROLE_WAITING = 3
)
